"""GDELT v2 column layouts and code lookups shared by the loader and the API."""

from __future__ import annotations

MENTION_COLUMNS = [
    "GlobalEventID",
    "EventTimeDate",
    "MentionTimeDate",
    "MentionType",
    "MentionSourceName",
    "MentionIdentifier",
    "SentenceID",
    "Actor1CharOffset",
    "Actor2CharOffset",
    "ActionCharOffset",
    "InRawText",
    "Confidence",
    "MentionDocLen",
    "MentionDocTone",
    "MentionDocTranslationInfo",
    "Extras",
]

EVENT_COLUMNS = [
    "GlobalEventID",
    "Day",
    "MonthYear",
    "Year",
    "FractionDate",
    *[
        f"{actor}{suffix}"
        for actor in ["Actor1", "Actor2"]
        for suffix in [
            "Code",
            "Name",
            "CountryCode",
            "KnownGroupCode",
            "EthnicCode",
            "Religion1Code",
            "Religion2Code",
            "Type1Code",
            "Type2Code",
            "Type3Code",
        ]
    ],
    "IsRootEvent",
    "EventCode",
    "EventBaseCode",
    "EventRootCode",
    "QuadClass",
    "GoldsteinScale",
    "NumMentions",
    "NumSources",
    "NumArticles",
    "AvgTone",
    *[
        f"{geo}_{suffix}"
        for geo in ["Actor1Geo", "Actor2Geo", "ActionGeo"]
        for suffix in [
            "Type",
            "FullName",
            "CountryCode",
            "ADM1Code",
            "ADM2Code",
            "Lat",
            "Long",
            "FeatureID",
        ]
    ],
    "DATEADDED",
    "SOURCEURL",
]

QUAD_CLASSES = {
    1: "Verbal Cooperation",
    2: "Material Cooperation",
    3: "Verbal Conflict",
    4: "Material Conflict",
}

# CAMEO root codes (first two digits of EventCode).
EVENT_ROOT_CODES = {
    "01": "Make Public Statement",
    "02": "Appeal",
    "03": "Express Intent To Cooperate",
    "04": "Consult",
    "05": "Engage In Diplomatic Cooperation",
    "06": "Engage In Material Cooperation",
    "07": "Provide Aid",
    "08": "Yield",
    "09": "Investigate",
    "10": "Demand",
    "11": "Disapprove",
    "12": "Reject",
    "13": "Threaten",
    "14": "Protest",
    "15": "Exhibit Force Posture",
    "16": "Reduce Relations",
    "17": "Coerce",
    "18": "Assault",
    "19": "Fight",
    "20": "Use Unconventional Mass Violence",
}

# Three-letter source-language codes GDELT writes into MentionDocTranslationInfo.
LANGUAGE_NAMES = {
    "ara": "Arabic",
    "ben": "Bengali",
    "bul": "Bulgarian",
    "cat": "Catalan",
    "ces": "Czech",
    "dan": "Danish",
    "deu": "German",
    "ell": "Greek",
    "eng": "English",
    "est": "Estonian",
    "fas": "Persian",
    "fin": "Finnish",
    "fra": "French",
    "heb": "Hebrew",
    "hin": "Hindi",
    "hrv": "Croatian",
    "hun": "Hungarian",
    "ind": "Indonesian",
    "isl": "Icelandic",
    "ita": "Italian",
    "jpn": "Japanese",
    "kor": "Korean",
    "lav": "Latvian",
    "lit": "Lithuanian",
    "msa": "Malay",
    "nld": "Dutch",
    "nor": "Norwegian",
    "pol": "Polish",
    "por": "Portuguese",
    "ron": "Romanian",
    "rus": "Russian",
    "slk": "Slovak",
    "slv": "Slovenian",
    "som": "Somali",
    "spa": "Spanish",
    "sqi": "Albanian",
    "srp": "Serbian",
    "swe": "Swedish",
    "tha": "Thai",
    "tur": "Turkish",
    "ukr": "Ukrainian",
    "urd": "Urdu",
    "vie": "Vietnamese",
    "zho": "Chinese",
}

# Country-code top level domains, used only to approximate DOC API `sourcecountry`.
TLD_COUNTRIES = {
    "ae": "United Arab Emirates",
    "af": "Afghanistan",
    "ar": "Argentina",
    "at": "Austria",
    "au": "Australia",
    "bd": "Bangladesh",
    "be": "Belgium",
    "bg": "Bulgaria",
    "br": "Brazil",
    "ca": "Canada",
    "ch": "Switzerland",
    "cl": "Chile",
    "cn": "China",
    "co": "Colombia",
    "cy": "Cyprus",
    "cz": "Czech Republic",
    "de": "Germany",
    "dk": "Denmark",
    "eg": "Egypt",
    "es": "Spain",
    "fi": "Finland",
    "fr": "France",
    "gh": "Ghana",
    "gr": "Greece",
    "hk": "Hong Kong",
    "hr": "Croatia",
    "hu": "Hungary",
    "id": "Indonesia",
    "ie": "Ireland",
    "il": "Israel",
    "in": "India",
    "iq": "Iraq",
    "ir": "Iran",
    "is": "Iceland",
    "it": "Italy",
    "jp": "Japan",
    "ke": "Kenya",
    "kr": "South Korea",
    "lk": "Sri Lanka",
    "lt": "Lithuania",
    "lv": "Latvia",
    "ma": "Morocco",
    "mx": "Mexico",
    "my": "Malaysia",
    "ng": "Nigeria",
    "nl": "Netherlands",
    "no": "Norway",
    "nz": "New Zealand",
    "pe": "Peru",
    "ph": "Philippines",
    "pk": "Pakistan",
    "pl": "Poland",
    "pt": "Portugal",
    "qa": "Qatar",
    "ro": "Romania",
    "rs": "Serbia",
    "ru": "Russia",
    "sa": "Saudi Arabia",
    "se": "Sweden",
    "sg": "Singapore",
    "si": "Slovenia",
    "sk": "Slovakia",
    "th": "Thailand",
    "tr": "Turkey",
    "tw": "Taiwan",
    "tz": "Tanzania",
    "ua": "Ukraine",
    "ug": "Uganda",
    "uk": "United Kingdom",
    "uy": "Uruguay",
    "ve": "Venezuela",
    "vn": "Vietnam",
    "za": "South Africa",
    "zm": "Zambia",
    "zw": "Zimbabwe",
}
